### ISSUE TITLE
Change /home/Akumanory to "~" or smth

### ISSUE THREAD

**Issue by vlad-ostas** [Akumanory/nvchad-config#1]
https://github.com/Akumanory/nvchad-config/blob/cf056297eac8106dbd7a52e0cae1a6f06cef9760/configs/cmake-tools.lua#L14C23-L14C37

**Comment by Akumanory** [comment]
Fixed: https://github.com/Akumanory/nvchad-config/commit/dc89373373ad06a149420a91ba26c4254b02a57d
